<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * P4: the deterministic QR verification token of an application
     * (`qr_token`, generated by `QrTokenService`). Nullable so existing
     * approved rows stay valid; the token is backfilled lazily on approval /
     * first read. The unique index is portable across Postgres and SQLite
     * (multiple NULLs are distinct in both).
     */
    public function up(): void
    {
        Schema::table('applications', function (Blueprint $table) {
            $table->string('qr_token')->nullable();
            $table->unique('qr_token');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('applications', function (Blueprint $table) {
            $table->dropUnique(['qr_token']);
            $table->dropColumn('qr_token');
        });
    }
};
